/* CoolCalci Phase 2 — authentication, cloud history, entitlements and secure usage bridge. */
(function () {
  'use strict';
  const CFG = window.COOLCALCI_SUPABASE_CONFIG || {};
  const KEY = 'coolcalci_phase1_v5';
  const supabaseLib = window.supabase;
  const configured = !!(supabaseLib && CFG.url && CFG.publishableKey && !String(CFG.publishableKey).startsWith('REPLACE_'));
  const $ = id => document.getElementById(id);
  let client = null, mode = 'signin', busy = false, bypassNextSubmit = false;
  const localState = () => { try { return JSON.parse(localStorage.getItem(KEY)||'null') || {history:[],saved:[],usage:0,day:new Date().toISOString().slice(0,10),plan:'free'}; } catch (_) { return {history:[],saved:[],usage:0,day:new Date().toISOString().slice(0,10),plan:'free'}; } };
  const writeState = s => { try { localStorage.setItem(KEY, JSON.stringify(s)); } catch (_) {} };
  const toast = msg => { const t=$('toast'); if(!t)return; t.textContent=msg; t.classList.add('show'); clearTimeout(window.__ccToast2); window.__ccToast2=setTimeout(()=>t.classList.remove('show'),2600); };
  const normalizePlan = p => p==='pro_monthly'||p==='pro-monthly'?'pro-monthly':p==='pro_yearly'||p==='pro-yearly'?'pro-yearly':'free';
  const retentionDate = (p,ms=Date.now()) => { const d=new Date(ms); p=normalizePlan(p); if(p==='pro-yearly')d.setFullYear(d.getFullYear()-1); else if(p==='pro-monthly')d.setMonth(d.getMonth()-1); else d.setTime(d.getTime()-86400000); return d; };
  function openAuth(){const o=$('authOverlay');if(!o)return;o.classList.add('open');o.setAttribute('aria-hidden','false');$('authEmail')?.focus();}
  function closeAuth(){const o=$('authOverlay');if(!o)return;o.classList.remove('open');o.setAttribute('aria-hidden','true');}
  function status(m,e){const x=$('authStatus');if(!x)return;x.textContent=m||'';x.classList.toggle('error',!!e);}
  function setMode(next){mode=next;const signup=mode==='signup';$('signInTab')?.classList.toggle('active',!signup);$('signUpTab')?.classList.toggle('active',signup);if($('nameLabel'))$('nameLabel').hidden=!signup;if($('authSubmit'))$('authSubmit').textContent=signup?'Create account':'Sign in';if($('authTitle'))$('authTitle').textContent=signup?'Create your CoolCalci account':'Sign in to CoolCalci';if($('authSubtitle'))$('authSubtitle').textContent=signup?'Keep your calculations synced across devices.':'Sync your history and saved calculations across devices.';status('');}
  function renderAuthUser(user){const area=$('authArea');if(!area)return;if(!user){area.innerHTML='<button class="auth-button" id="authBtn">Sign in</button>';$('authBtn').onclick=openAuth;return;}const email=String(user.email||'Signed-in user');const safe=email.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));area.innerHTML=`<div class="auth-user"><span class="cloud-badge"><span class="cloud-dot"></span>Cloud sync</span><small title="${safe}">${safe}</small><button class="auth-button" id="signOutBtn">Sign out</button></div>`;$('signOutBtn').onclick=async()=>{await client?.auth.signOut();toast('Signed out');};}
  async function getEntitlement(){if(!client)return{plan:'free',role:'user',status:'active',historyRetentionDays:1,unlimitedCalculations:false};const{data,error}=await client.rpc('get_my_entitlement');if(error){console.error('CoolCalci entitlement:',error);return{plan:'free',role:'user',status:'active',historyRetentionDays:1,unlimitedCalculations:false};}const row=Array.isArray(data)?data[0]:data;return{plan:normalizePlan(row?.plan),role:row?.role||'user',status:row?.status||'active',historyRetentionDays:Number(row?.history_retention_days||1),unlimitedCalculations:!!row?.unlimited_calculations};}
  function applyEntitlement(ent){const s=localState();s.plan=normalizePlan(ent?.plan);s.role=ent?.role||'user';s.unlimitedCalculations=!!ent?.unlimitedCalculations;writeState(s);document.dispatchEvent(new CustomEvent('coolcalci:entitlement',{detail:ent}));}
  async function loadCloudData(user,ent){if(!client||!user)return;const cutoff=retentionDate(ent?.plan).toISOString();const[h,s]=await Promise.all([client.from('calculation_history').select('id,query,title,result,formula,created_at').eq('user_id',user.id).gte('created_at',cutoff).order('created_at',{ascending:false}).limit(200),client.from('saved_calculations').select('id,query,title,result,formula,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(200)]);const st=localState();if(!h.error)st.history=h.data.map(x=>({q:x.query,title:x.title,r:x.result,f:x.formula,time:new Date(x.created_at).getTime(),cloudId:x.id}));if(!s.error)st.saved=s.data.map(x=>({q:x.query,title:x.title,r:x.result+' · '+(x.formula||''),time:new Date(x.created_at).getTime(),cloudId:x.id}));writeState(st);document.dispatchEvent(new CustomEvent('coolcalci:cloud-data-loaded'));document.dispatchEvent(new CustomEvent('coolcalci:render-request'));}
  async function migrateLocalData(user){if(!client||!user)return;const st=localState();if(st.__cloudMigrated)return;const h=(st.history||[]).slice(0,200).map(x=>({user_id:user.id,query:x.q||x.title||'Calculation',title:x.title||'Calculation',result:x.r||'',formula:x.f||null,created_at:new Date(x.time||Date.now()).toISOString()})).filter(x=>x.result);const s=(st.saved||[]).slice(0,200).map(x=>{const p=String(x.r||'').split(' · ');return{user_id:user.id,query:x.q||x.title||'Calculation',title:x.title||'Calculation',result:p.shift()||'',formula:p.join(' · ')||null,created_at:new Date(x.time||Date.now()).toISOString()};}).filter(x=>x.result);if(h.length)await client.from('calculation_history').insert(h);if(s.length)await client.from('saved_calculations').insert(s);st.__cloudMigrated=true;writeState(st);}
  async function syncLatestCalculation(user){if(!client||!user)return;const st=localState(),x=st.history?.[0];if(!x)return;const marker=`${x.time}:${x.q}:${x.r}`;if(sessionStorage.getItem('cc_last_synced_calc')===marker)return;const{data,error}=await client.from('calculation_history').insert({user_id:user.id,query:x.q||x.title||'Calculation',title:x.title||'Calculation',result:x.r||'',formula:x.f||null,created_at:new Date(x.time||Date.now()).toISOString()}).select('id').single();if(!error){x.cloudId=data?.id||x.cloudId;st.history[0]=x;writeState(st);sessionStorage.setItem('cc_last_synced_calc',marker);}}
  async function syncSavedCalculation(user){if(!client||!user)return;const st=localState(),x=st.saved?.[0];if(!x)return;const marker=`${x.time}:${x.q}:${x.r}`;if(sessionStorage.getItem('cc_last_synced_saved')===marker)return;const raw=String(x.r||''),parts=raw.split(' · ');const{data,error}=await client.from('saved_calculations').insert({user_id:user.id,query:x.q||x.title||'Calculation',title:x.title||'Calculation',result:parts.shift()||raw,formula:parts.join(' · ')||null,created_at:new Date(x.time||Date.now()).toISOString()}).select('id').single();if(!error){x.cloudId=data?.id||x.cloudId;st.saved[0]=x;writeState(st);sessionStorage.setItem('cc_last_synced_saved',marker);}}
  async function deleteCloudSavedByLocalIndex(i){if(!client)return false;const st=localState(),x=st.saved?.[i];if(!x)return false;const{data:{session}}=await client.auth.getSession();if(!session?.user)return false;if(x.cloudId){const{error}=await client.from('saved_calculations').delete().eq('id',x.cloudId).eq('user_id',session.user.id);if(error)return false;}st.saved.splice(i,1);writeState(st);document.dispatchEvent(new CustomEvent('coolcalci:render-request'));return true;}
  async function deleteCloudHistoryByLocalIndex(i){if(!client)return false;const st=localState(),x=st.history?.[i];if(!x)return false;const{data:{session}}=await client.auth.getSession();if(!session?.user)return false;if(x.cloudId){const{error}=await client.from('calculation_history').delete().eq('id',x.cloudId).eq('user_id',session.user.id);if(error)return false;}st.history.splice(i,1);writeState(st);document.dispatchEvent(new CustomEvent('coolcalci:render-request'));return true;}
  window.coolCalciPhase2={deleteCloudSavedByLocalIndex,deleteCloudHistoryByLocalIndex,refresh:async()=>{if(!client)return;const{data:{session}}=await client.auth.getSession();if(session?.user){const ent=await getEntitlement();applyEntitlement(ent);await loadCloudData(session.user,ent);}}};
  async function consumeServerQuota(user){if(!client||!user)return true;const{data,error}=await client.rpc('consume_calculation');if(error){toast('Cloud usage check is not ready yet. Please try again shortly.');console.error('CoolCalci usage RPC:',error);return false;}const row=Array.isArray(data)?data[0]:data;if(!row?.allowed){toast(`Daily free limit reached (${row?.daily_limit||3} calculations).`);return false;}return true;}
  async function handleSubmitCapture(e){if(bypassNextSubmit||busy||!client)return;const{data:{session}}=await client.auth.getSession();if(!session?.user)return;const st=localState();if(st.unlimitedCalculations)return;e.preventDefault();e.stopImmediatePropagation();busy=true;const allowed=await consumeServerQuota(session.user);if(allowed){bypassNextSubmit=true;e.target.requestSubmit();bypassNextSubmit=false;}busy=false;}
  async function submitAuth(e){e.preventDefault();if(!configured||!client){status('Supabase publishable key is not configured yet.',true);return;}const email=$('authEmail').value.trim(),password=$('authPassword').value,name=$('authName').value.trim();if(!email||password.length<6){status('Enter a valid email and a password of at least 6 characters.',true);return;}status(mode==='signup'?'Creating your account…':'Signing you in…');$('authSubmit').disabled=true;const r=mode==='signup'?await client.auth.signUp({email,password,options:{data:{full_name:name||undefined}}}):await client.auth.signInWithPassword({email,password});$('authSubmit').disabled=false;if(r.error){status(r.error.message,true);return;}if(mode==='signup'&&!r.data.session){status('Account created. Check your email to confirm your address, then sign in.');return;}closeAuth();}
  async function startGoogle(){if(!configured||!client){status('Supabase publishable key is not configured yet.',true);return;}status('Opening Google sign-in…');const{error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+window.location.pathname}});if(error)status(error.message,true);}
  function bindUi(){$('authBtn')?.addEventListener('click',openAuth);$('authClose')?.addEventListener('click',closeAuth);$('authOverlay')?.addEventListener('click',e=>{if(e.target===$('authOverlay'))closeAuth();});$('signInTab')?.addEventListener('click',()=>setMode('signin'));$('signUpTab')?.addEventListener('click',()=>setMode('signup'));$('authForm')?.addEventListener('submit',submitAuth);$('googleBtn')?.addEventListener('click',startGoogle);$('calcForm')?.addEventListener('submit',handleSubmitCapture,true);$('calcForm')?.addEventListener('submit',async()=>{const{data:{session}}=await client?.auth.getSession()||{data:{session:null}};if(session?.user)setTimeout(()=>syncLatestCalculation(session.user),0);});document.addEventListener('click',e=>{if(e.target.closest('[data-save]'))setTimeout(async()=>{const{data:{session}}=await client?.auth.getSession()||{data:{session:null}};if(session?.user)syncSavedCalculation(session.user);},20);});$('proCta')?.addEventListener('click',e=>{if(!client)return;e.preventDefault();e.stopImmediatePropagation();toast('Secure Pro activation will be connected with payments in the monetization phase.');},true);}
  async function boot(){bindUi();if(!configured){renderAuthUser(null);return;}client=supabaseLib.createClient(CFG.url,CFG.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});window.coolcalciSupabase=client;const{data:{session}}=await client.auth.getSession();if(session?.user){const ent=await getEntitlement();applyEntitlement(ent);renderAuthUser(session.user);await migrateLocalData(session.user);await loadCloudData(session.user,ent);}else renderAuthUser(null);client.auth.onAuthStateChange(async(_event,nextSession)=>{if(nextSession?.user){const ent=await getEntitlement();applyEntitlement(ent);renderAuthUser(nextSession.user);await migrateLocalData(nextSession.user);await loadCloudData(nextSession.user,ent);toast('Account connected. Cloud sync is on.');}else{applyEntitlement({plan:'free',role:'user',unlimitedCalculations:false});renderAuthUser(null);}});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
